# Where your server list is stored
serverListFile: '{rootDir}/serverlist.yml'

# Display console messages
displayConsoleMessages: false

# List of disabled kirin commands
disabledCommands: []

# Start options
start:
  enabled: true
  addButton: true
  allowedPermissions: ['VIEW_CHANNEL']
  allowedRoles: []

# Stop options
stop:
  enabled: true
  addButton: true
  allowedPermissions: ['ADMINISTRATOR']
  allowedRoles: []

# Restart server options (Experimental and not recommended)
restart:
  enabled: false
  addButton: true
  allowedPermissions: ['ADMINISTRATOR']
  allowedRoles: []

# Stop servers when the bot stopped
stopServerOnExit: false

# Stop signal
# DON'T CHANGE THIS IF YOU DON'T KNOW WHAT YOU ARE DOING
stopSignal: 'SIGINT'

# Limit the number of online servers
# If you set this to 0, there is no limit
onlineServersLimit: 0

# Delete disabled buttons
deleteDisabledButtons: true

# Options for pinging servers
pingServers:
  # Add status fields to server message embeds
  displayServerStatus: true

  # Disable start buttons when the server is online
  disableStartButtonWhenOnline: true

  # Disable stop buttons when the server is offline
  disableStopButtonWhenOffline: true

  # Server ping interval
  pingIntervalMilliseconds: 5000

  # Ping connection timeout in milliseconds
  pingTimeoutMilliseconds: 5000

  # Mark server with 0 max players as offline
  zeroMaxServersAsOffline: true

# You can edit embed status fields here
messages:
  status:
    online: 'Online'
    offline: 'Offline'
  fieldTitles:
    status: 'Status'
    players: 'Players'
    version: 'Version'
  buttons:
    start: 'Start'
    stop: 'Stop'
    restart: 'Restart'
  errors:
    onlineServersLimitMessage:
      content: 'The maximum number of online servers has been reached.'
      ephemeral: true
    stop:
      content: 'Could not stop server'
      ephemeral: true
    start:
      content: 'Could not start server'
      ephemeral: true
  process:
    disabled:
      content: 'This action is disabled'
      ephemeral: true
    alreadyRunning:
      content: 'Server is already running or starting'
      ephemeral: true
    notRunning:
      content: 'Server is not running'
      ephemeral: true
    starting:
      content: 'Starting server...'
      ephemeral: true
    stopping:
      content: 'Stopping server...'
      ephemeral: true
    restarting:
      content: 'Restarting server...'
      ephemeral: true
    noPermissions:
      content: 'You do not have the required permissions to do this action'
      ephemeral: true