# Where your server list is stored
serverListFile: '{rootDir}/serverlist.yml'

# Discord permissions needs to start the servers
serverStartPermissions: ['SEND_MESSAGES']

# Display console messages
displayConsoleMessages: false

# Add stop button
addStopButton: true

# Discord permissions needs to stop the servers
serverStopPermissions: ['ADMINISTRATOR']

# Options for pinging servers
pingServers:
  # Add status fields to server message embeds
  displayServerStatus: true

  # Disable start buttons when the server is online
  disableStartButtonWhenOnline: true

  # Disable stop buttons when the server is offline
  disableStopButtonWhenOffline: true

  # Server ping interval
  pingIntervalMilliseconds: 60000

  # Ping connection timeout in milliseconds
  pingTimeoutMilliseconds: 5000

  # Mark server with 0 max players as offline
  zeroMaxServersAsOffline: true

# You can edit embed status fields here
messages:
  status:
    online: 'Online'
    offline: 'Offline'
  fieldTitles:
    status: 'Status'
    players: 'Players'
    version: 'Version'
  buttons:
    start: 'Start'
    stop: 'Stop'
  process:
    alreadyRunning:
      content: 'Server is already running or starting'
      ephemeral: true
    notRunning:
      content: 'Server is not running'
      ephemeral: true
    starting:
      content: 'Starting server...'
      ephemeral: true
    stopping:
      content: 'Stopping server...'
      ephemeral: true
    noPermissions:
      content: 'You do not have the required permissions to do this action'
      ephemeral: true